### ISSUE TITLE
Additional information needed in booking API (3sp)

### ISSUE THREAD

**Issue by koushik-chatterjee** [windingtree/wt-booking-api#14]
**Is your feature request related to a problem? Please describe.**
In the Booking API only total rate of a booking is mentioned without any information on rateplan id, price for each rateplans and dates, but when the reservation gets delivered to hotel system they would want these information to get delivered in their system.

**Describe the solution you'd like**
In the Booking API, we want the following information to be included,

1. Rateplan id for which the booking call is initiated
2. price amount for each date if it is multiple day booking
3. price for each rateplan if the booking is for multiple rateplans

**Comment by czervenka** [comment]
Thank you for your feedback, it's valuable for us. We were thinking about such information in booking request when we were designing the booking protocol.

**Comment by czervenka** [comment]
I moved OTA / distribution partner information out of this issue to windingtree/wt-booking-api#15
