### ISSUE TITLE
Trustworthy selling party identifier

### ISSUE THREAD

**Issue by czervenka** [windingtree/wt-booking-api#16]
When a hotel (or channel manager) receives a booking request it is missing a trustworthy information who is the partner (GDS or OTA) who initiated the booking on behalf of customer.

A possible solution would be to have an WT index of sellers (similar to the WT hotel index) and extend booking protocol by a possibility (or a requirement) to sign booking requests using a key associated with a seller entry in WT seller index on blockchain.

**Comment by JirkaChadima** [comment]
This is realized as part of #19 where we are adding a `originAddress` field which is Ethereum address uniquely identifying the source of the booking. That address is then taken through trust clues system to establish its trustworthines..
