### ISSUE TITLE
Booking spam protection

### ISSUE THREAD

**Issue by czervenka** [windingtree/wt-booking-api#19]
When a supplier (hotel) publishes an open booking API it is vulnerable to spam requests. 

Booking protocol should be complemented by a spam request protection (to limit number of spam requests).

Solution is yet to be proposed.

**Comment by JirkaChadima** [comment]
Applicable solutions - from the top of my head and a discussion we had earlier:

- throttling or rate limiting (https://www.npmjs.com/package/express-rate-limit)
- captcha (https://www.google.com/recaptcha/intro/v3.html)
- CSRF tokens (https://stackoverflow.com/questions/5207160/what-is-a-csrf-token-what-is-its-importance-and-how-does-it-work)
- pre-registration of API callees - either with the platform itself, or with a particular instancec of Booking API
- request signing
- OAuth (somehow)

The main problem we have is, that WT can only specify the protocol, it cannot force anyone to use a certain implementation or a technical solution. On the other hand, the implementations must be able to accept bookings from the wild. So this is essentially an M:N Authentication problem without a central authority.

Definitely related: https://github.com/windingtree/wt-booking-api/issues/16
Remotely related: https://github.com/windingtree/wt-write-api/issues/8
Kind of related: https://groups.google.com/forum/#!topic/windingtree/tsfBvMrXxjg, https://github.com/windingtree/wt-notification-api/issues/1

**Comment by czervenka** [comment]
@JirkaChadima will write what we agreed on planning meeting.

**Comment by JirkaChadima** [comment]
Meeting notes follow:

As WT:
- We cannot force anyone to implement any particular technical measure.
- We have to define security measures on the protocol level.

As an operator of an instance of Booking API:
- I should be using throttling regardless of any security measures in place.
- To efficiently work with the incoming traffic, I need to know the identity of the API caller.
- I need to be able to independently verifiy the caller's identity.
- The identity cannot be spoofed in the message (message signing probably has to be in place).
- Based on attributes of the provided identity, I can behave accordingly (refuse request, enforce more security measures etc.).
- If I cannot verify the caller identity but still want to accept the requests, I might want to enforce a guarantee from the caller (e. g. some form of staking - payment details, immediate payment, deposit).
- If I cannot verify the caller identity but still want to allow real actual humans to do "unauthorized" bookings, some anti-bot barrier might make sense (e. g. captcha, but we cannot limit it to a single provider).

General:
- There is probably no one-size-fits-all solution, we need to come up with a parameterizable one based on the level of trust between booking API provider and the booking identity.

**Comment by czervenka** [comment]
This issue is being solved as part of https://github.com/orgs/windingtree/projects/4 project

**Comment by JirkaChadima** [comment]
Another option might be to protect the Booking API with some standard HTTP-based authentication mechanism. The drawback of this solution is that the clients have to be adapted to handle such situations gracefully, even when there's user input needed.
