### ISSUE TITLE
#31: Disclosing Booking API trust rules

### ISSUE THREAD

**Issue by ondrejchmelar** [windingtree/wt-booking-api#31]
Assigned to @ondrejchmelar

**Story**: *As a Booking API caller, I want to know beforehand what do I have to do so the Booking API accepts my requests.*

---

- [x] includes whitelist
- [x] includes blacklist
- [x] includes trust level verification with public key registry
- [x] requires the Booking API caller to send a signed request to the Booking API, ~~the response contains how the hotel will handle this particular identity~~

**Comment by JirkaChadima** [comment]
Related to #28

**Comment by ondrejchmelar** [comment]
https://github.com/windingtree/wt-booking-api/pull/28
